### ISSUE TITLE
OBJ loader loads Vertex Normals as Vertexes

### ISSUE THREAD

**Issue by rrix** [jamesgregson/pyPolyCSG#12]
OBJ file format lets you set a bunch of vertex properties using various entities which start with v:

```
# List of Vertices, with (x,y,z[,w]) coordinates, w is optional and defaults to 1.0.
v 0.123 0.234 0.345 1.0
v ...
...
# Texture coordinates, in (u ,v [,w]) coordinates, these will vary between 0 and 1, w is optional and default to 0.
vt 0.500 1 [0]
vt ...
...
# Normals in (x,y,z) form; normals might not be unit.
vn 0.707 0.000 0.707
vn ...
...
# Parameter space vertices in ( u [,v] [,w] ) form; free form geometry statement ( see below )
vp 0.310000 3.210000 2.100000
vp ...
...
```

https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format

Your vertex loader only checks that the lines start with V and then load the coordinates in to vertex objects; These entities above should probably be filtered out using no-op's like so:

```
while( !(getline(input,line)).fail() ){
    if ( line[0] == 'v' && line[1] == 'n') {
        // No-op; ignore vertex normals
    } else if( line[0] == 'v' ){
```

**Comment by jamesgregson** [comment]
This is definitely an issue, I'll add these changes in.

**Comment by jamesgregson** [comment]
I've added this change in now that I've finally been able to update to a more recent version of Carve.  It now checks that the character following the leading 'v' is a space, which should handle vt/vp/vn.

Thanks for pointing this out.
