### ISSUE TITLE
Bug test: CSG subtraction is unreliable

### ISSUE THREAD

**Issue by dbc** [jamesgregson/pyPolyCSG#8]
Update: So I recalled that I had never run the Carve library tests in the build directory.  Several of those fail for me. So perhaps there is some sort of build problem with Linux.  Anyway... will not have time to diagnose it further until next week.

Original post:

The test below repeatedly subtracts a cylinder from a block at varied offsets. Very often, pyPolyCSG throws an 'unidentifiable C++ exception'.  But not consistently.

```
>>> ================================ RESTART ================================
>>> 
passed 840
failures:
360 : unidentifiable C++ exception
>>> ================================ RESTART ================================
>>> 
passed 841
failures:
359 : unidentifiable C++ exception
>>> ================================ RESTART ================================
>>> 
passed 836
failures:
364 : unidentifiable C++ exception
>>> ================================ RESTART ================================
>>> 
passed 832
failures:
368 : unidentifiable C++ exception
>>> ================================ RESTART ================================
>>> 
passed 837
failures:
363 : unidentifiable C++ exception
```

The test script is:

```
# Reliability test for csg subtraction.
# Constructs a block and a cylinder, and repeatedly subtracts
# the cylinder from the box at different locations.

import pyPolyCSG as csg

ctrlDiameter = {'start':0.5, 'end':1.51, 'step':0.25 }
ctrlStep = {'start':0.5, 'end':1.51, 'step':0.25 }
ctrlDepth = {'start':1.5, 'end':3.51, 'step':0.5 }

passes = 0
fails = {}

diameter = ctrlDiameter['start']
while diameter < ctrlDiameter['end']:
    # Create a cylinder
    # print 'diameter',diameter
    cyl = csg.cylinder(diameter,4,True)
    depth = ctrlDepth['start']
    while depth < ctrlDepth['end']:
        # print 'depth',depth
        # Set the cylinder depth
        cylAtDepth = cyl.translate(0,depth,0) 
        # Create a box
        block = csg.box(6,2,4,True)
        step = ctrlStep['start']
        while step < ctrlStep['end']:
            # print 'step',step
            # perform the cutting pass
            offset = 4.0
            while offset > -4.0:
                tool = cylAtDepth.translate(offset,0,0)
                try:
                    block -= tool
                    status = 'pass'
                    msg = ''
                    passes += 1
                except Exception as ex:
                    status = 'fail'
                    msg = str(ex)
                    if msg in fails:
                        fails[msg] += 1
                    else:
                        fails[msg] = 1
                offset -= step
            step += ctrlStep['step']
        depth += ctrlDepth['step']
    diameter += ctrlDiameter['step']

print 'passed',passes
print 'failures:'
for msg, count in fails.items():
    print count, ':', msg
```

Almost certainly this is coming from Carve.  But we need to verify that it is not a bug in pyPolyCSG, then try the development head for Carve to see if the bug is still there, and then probably code up the equivalent test in C++ and file an issue against Carve.

I've noticed that rotating the cylinder slightly will move the failure around. 

Since this failure is inconsistent, it could very well be an uninitialized variable in Carve.  Perhaps a build of Carve with optimization off is worth a shot -- if the bug goes away with optimization off then that is a good indicator if an uninitialized variable.

**Comment by jamesgregson** [comment]
I've updated the library to a more recent version of Carve, which appears to be considerably more robust.  Although it does not pass this test, however it does do much better: 1176 operations pass and 24 fail as compared to 836 pass and 367 fail.

It also seems to be quite a bit faster.

The build instructions for the update have changed a bit, carve can now be directly downloaded from the Google Code mercurial repository.  Instructions are updated in the README.
